INPUT_DATE_FORMAT = '%Y-%m-%d'
OUTPUT_DATE_FORMAT = '%Y-%m-%d'
DATE_FORMAT = '%Y-%m-%d'

# Market Data Names
OPEN_COLUMN = 'Open'
CLOSE_COLUMN = 'Close'
HIGH_COLUMN = 'High'
LOW_COLUMN = 'Low'
VOLUME_COLUMN = 'Volume'
DATE_COLUMN = 'Date'
SYMBOL_COLUMN = 'Symbol'

BUYPRICE_COLUMN = 'BuyPrice'
SELLPRICE_COLUMN = 'SellPrice'
INDICATOR_COLUMN = 'Indicator'

# Folder names
USERDATA_FOLDER = 'user_data'
USERINPUT_FOLDER = 'user_inputs'
MARKETDATA_FOLDER = 'stock_dfs'
BUYINFO_FOLDER = 'buy_info'
PORTVAL_FOLDER = 'portfolio_val'
WEIGHTS_FOLDER = 'weights'
LOGFILE = 'user_data/trace.log'

# Backtest result or statistics names
TEST_NAME_PREFIX = 'BackTest'
CASH = 'CASH'
HOLDING = 'HOLDING'
PORTFOLIO = 'PORTFOLIO'
LEVERAGE = 'LEVERAGE'
DRAWDOWN = 'DRAWDOWN'
BOUGHT = 'BOUGHT'
RETURNS = 'RETURNS'
BETA = 'BETA'
ALPHA = 'ALPHA'
SHARPE = 'SHARPE'
START = 'START'
END = 'END'
COVERAGE = 'COVERAGE'
TRADES = 'TRADES'
WINS = 'WINS'
LOSS = 'LOSS'
POTENTIALTRADES = 'POTENTIALTRADES'
NOTRADESFORVOLUME = 'NOTRADESFORVOLUME'
NOTRADESFORCASH = 'NOTRADESFORCASH'
LOSTSALE = 'LOSTSALE'
LOWESTPOINT = 'LOWESTPOINT'
TURNOVER = 'TURNOVER'
LEVERAGE = 'LEVERAGE'
CASHUSED = 'CASHUSED'
HOLDINGS = 'HOLDINGS'
POSITION = 'POSITION'
PERIOD = 'PERIOD'
ACTUALPORTFOLIO = 'ACTUALPORTFOLIO'
PORTFOLIO = 'PORTFOLIO'
GAIN_LOSS = 'GAIN_LOSS'
UNITPRICE = 'UNITPRICE'
VOLATILITY = 'VOLATILITY'

#Activity
SYMBOL = 'SYMBOL'
SELLDATE = 'SELLDATE'
BUYPRICE = 'BUYPRICE'
SELLPRICE = 'SELLPRICE'
QUANTITY = 'QUANTITY'
FAIL_REASON = 'FAIL_REASON'

#benchmark
BENCHMARK = 'SPY'

#learner
NUM_ACTIONS = 3
ALPHA = 0.2
GAMMA = 0.9
RAR = 0.5
RADR = 0.8
RARM = 0.01

IMPACT = 0.005
SV = 100000
BINS = 5
COMMISSION=9.95

#convergence variables
MIN_ITER = 20
MAX_ITER = 100

#portfolio variables
RFR = 0 #riskfree rate

BATCH_SIZE = 32

IPO_DATA = 'ipo_dates'

NUM_STATES = 4







